version: '3'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.prod
    image: alice-domofon:v0.1
    container_name: alice_domofon
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: "postgres://postgres:postgres@db/postgres"
    env_file:
      - .env.prod
    depends_on:
      - db
    volumes:
      - ./ssl:/ssl
      - ./app/static/html:/app/app/static/html

  db:
    image: postgres:11.5-alpine
    ports:
      - "5442:5432"
    env_file:
      - .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
